### ISSUE TITLE
Create extra permission to pantheon apache solr settings

### ISSUE THREAD

**Issue by jacintocapote** [pantheon-systems/drops-7#43]
I create a little patch for pantheon apache solr. https://gist.github.com/jacintocapote/b6a8d848f91f00c49881
The patch add a new permission to access to administer pages of pantheon apache solr. Because the module use 'access administer pages' but we have a case where the user can access to some administer pages and not to pantheon apache solr settings.

**Comment by timani** [comment]
@greg-1-anderson + @joshkoenig This came up again, any chance we can get this in the next release for Drops 7

**Comment by nadavoid** [comment]
This can be a confusing issue because you can be logged in as a highly privileged user, but not User 1, and not have access to pantheon solr settings. This is definitely an issue if core search has never been enabled or its admin permissions granted to anyone.

The linked patch will need to be updated because today, instead of using the permission 'access administration pages', the permission 'administer search' is used.

**Comment by joshkoenig** [comment]
Let's get this into a PR and on-deck for the next point-release from upstream.

**Comment by nadavoid** [comment]
Pull request created, #76.

**Comment by scottbuscemi** [comment]
Closing as stale. Please re-open if needed.
