### ISSUE TITLE
pantheon_apachesolr is unable to post schema 

### ISSUE THREAD

**Issue by bwood** [pantheon-systems/drops-7#53]
On panopoly-based sites (at least) pantheon_apachesolr fails to import the schema. This results in errors like this one on install:

```
WD pantheon_apachesolr: Error Could not resolve host:                    [error]
index.live.getpantheon.com posting
profiles/openberkeley/modules/contrib/search_api_solr/solr-conf/3.x/schema.xml
to
https://index.live.getpantheon.com/sites/self/environments/dev/index
```

That error recurs if you try to use the form at /admin/config/search/pantheon/schema to post the schema.

I believe the variable pantheon_tier is not getting set correctly. Notice this output on a _dev_ site:

```
[bwood@mbp tmp]$ drush @pantheon.openucb-586.dev vget pantheon_tier
pantheon_tier: "live"

[bwood@mbp tmp]$ drush @pantheon.openucb-586-panopoly.dev vget pantheon_tier
pantheon_tier: "live"
```

And I can't simply change that:

```
[bwood@mbp tmp]$ drush @pantheon.openucb-586.dev vset pantheon_tier dev
pantheon_tier was set to "dev".                                        [success]
[bwood@mbp tmp]$ drush @pantheon.openucb-586.dev vget pantheon_tier
pantheon_tier: "live"
```

**Comment by nstielau** [comment]
Hey, that is confusing.  The domain ‘index.live.getpantheon.com’ is a
legacy domain that does exist/work anymore, dating back to the days when we
had a single Solr server.  Now, we have several Solr service endpoints, and
one is chosen for your site when you add Solr.  When a Solr service
endpoint is chosen for your site, the ‘pantheon_index_host’ variable will
be set in PHP, which is read by DROPS-7.

You can read up on how to add Solr here:
https://www.getpantheon.com/docs/articles/sites/apache-solr/

I’ll make a ticket about making DROPS-7 be a little more clear, rather than
falling back to a domain that doesn’t exist.

On Mon, Feb 2, 2015 at 2:22 PM, Brian Wood <notifications@github.com> wrote:
>
> On panopoly-based sites (at least) pantheon_apachesolr fails to import
the schema. This results in errors like this one on install:
>
> WD pantheon_apachesolr: Error Could not resolve host:
 [error]
> index.live.getpantheon.com posting
>
profiles/openberkeley/modules/contrib/search_api_solr/solr-conf/3.x/schema.xml
> to
> https://index.live.getpantheon.com/sites/self/environments/dev/index
>
> That error recurs if you try to use the form at
/admin/config/search/pantheon/schema to post the schema.
>
> I believe the variable pantheon_tier is not getting set correctly:
>
> [bwood@mbp tmp]$ drush @pantheon.openucb-586.dev vget pantheon_tier
> pantheon_tier: "live"
>
> [bwood@mbp tmp]$ drush @pantheon.openucb-586-panopoly.dev vget
pantheon_tier
> pantheon_tier: "live"
>
> And I can't simply change that:
>
> [bwood@mbp tmp]$ drush @pantheon.openucb-586.dev vset pantheon_tier dev
> pantheon_tier was set to "dev".
 [success]
> [bwood@mbp tmp]$ drush @pantheon.openucb-586.dev vget pantheon_tier
> pantheon_tier: "live"
>
> —
> Reply to this email directly or view it on GitHub.




--
Nick Stielau
Director of Engineering
Pantheon Systems

**Comment by mikecrittenden** [comment]
I'm not sure what I'm doing wrong here, but the `pantheon_index_host` variable isn't getting set for me at all. I've tried uninstalling and re-installing the pantheon_apachesolr module with no help and I also don't see anything in the codebase that tries to set the `pantheon_index_host` variable. What am I missing?

**Comment by stevector** [comment]
@mikecrittenden Is Solr enabled on the Pantheon site?

![screen shot 2018-11-08 at 1 51 40 pm](https://user-images.githubusercontent.com/211029/48223879-d6341000-e35d-11e8-8028-4c4921f1dff8.png)

**Comment by mikecrittenden** [comment]
@stevector You beat my edit by like 5 seconds - yep that was the exact issue. I'm going to leave my stupidness here in case it helps someone else.

**Comment by scottbuscemi** [comment]
Closing as stale. Please re-open if needed.
